### ISSUE TITLE
Remove object's own 'id' property from the anoncreds data models

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/anoncreds-spec#104]
As discussed on the AnonCreds implementers call on 2022-11-07, there is no need to add the identifiers to the AnonCreds objects, this is just an external value and a reference to the object. 

Discussion: https://github.com/hyperledger/anoncreds-rs/issues/4

**Comment by swcurran** [comment]
To clarify -- this is the "self" ID for an object.

The task of doing this in the spec should be a pass made for addressing only this issue should be added to the roadmap.

**Comment by TimoGlastra** [comment]
> The task of doing this in the spec should be a pass made for addressing only this issue should be added to the roadmap.

What do you exactly mean with this sentence @swcurran?

**Comment by swcurran** [comment]
That we need a PR that is specific to addressing this issue in the spec. Removing the items from all the documents.  This is an attempt to reduce merge conflicts.  

At least I think that is what I meant.  I wrote that 4 days ago! 🤣

**Comment by rodolfomiranda** [comment]
Was that already resolved? I couldn't find the `own id` property on the objects but the legend that the identifier is dependent on where the object is published and the AnonCreds method used.

**Comment by swcurran** [comment]
Should be good then.  Closing this issue.
