### ISSUE TITLE
Validation of identifiers within AnonCreds objects

### ISSUE THREAD

**Issue by blu3beri** [hyperledger/anoncreds-spec#111]
@TimoGlastra and I had a discussion about the validation of identifiers used within the anoncreds-rs codebase. 

I created a PR https://github.com/hyperledger/anoncreds-rs/pull/25 that removes the creation and internal references to the id property inside the anoncreds object and I extract to a seperate string. With this I also removed the validation of the identifier as my understanding was that any identifier is allowed.

Timo pointed me to a section in the spec, https://hyperledger.github.io/anoncreds-spec/#anoncreds-identifiers , which mentions that identifiers SHOULD be validated. 

Now, @swcurran I guess the main question is, do we allow any kind of identifier and remove the validation (and change the part where we SHOULD validate) or can external identifiers only be URIs (or legacy) and we add the validation back?

**Comment by blu3beri** [comment]
As discussed in 12/12/2022 WG:

1. Identifiers MUST be validated
2. Identifier MUST be a URI (will cover current identifiers and legacy).

**Comment by rodolfomiranda** [comment]
what does validation means in this contexts?

**Comment by blu3beri** [comment]
Closed by #142
