### ISSUE TITLE
Remove WQL & define proof request restrictions format

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/anoncreds-spec#127]
See #118  for extra context.

This issue focusses on a) the removal of WQL from the AnonCreds specification, and b) defining the allowed fields in the `restrictions` field of a proof request. 

I think for backwards compatibility we should keep the fields ending in _did and only allow them for the legacy indy identifier use case. Other should use the _id variant.

The question is how far we want to go in supporting restrictions in the proof request. I think most aries implementations  have only implemented the following:
- schema_id
- cred_def_id
- schema_issuer_did
- schema_name
- schema_version
- issuer_did
- rev_reg_id
- attribute value query (`attr:<atttr_name>:value` -> `<value>`)

The current AnonCreds spec has a whole sections on WQL and suggests we can also use:
- $like for fuzzy search
- $gt, $lt, $gte, $lte for size comparison
- $in for matching that a value is in a set
- attribute existence query (`attr::<attribute name>::marker` -> `1`)

Implementing the above as well means it will be more like a competitor to the Presentation Exchange protocol that allows advanced filtering. 

Either way, I think we shouldn't call it Wallet Query Language, but rather call it something specific to proof request restrictions.

Some other notes:
- There's currently a mention of `~` for unencrypted tags. As that is more of an implementation detail we can remove this part completely

**Comment by swcurran** [comment]
Per discussion at AnonCreds spec. meeting 2023.01.09 -- closing, addressed by #128
