### ISSUE TITLE
Validation of anoncreds objects version

### ISSUE THREAD

**Issue by blu3beri** [hyperledger/anoncreds-spec#130]
I was curious if there is any validation we have to do, could not find it in the spec, with the anoncreds objects version. Do we allow any string? If we have no intention of validation of versions this can be marked as completed.

**Comment by TimoGlastra** [comment]
What do you mean with validation of the anoncreds version? Where is this present? Do you have an example?

**Comment by blu3beri** [comment]
> What do you mean with validation of the anoncreds version? Where is this present? Do you have an example?

Yeah should have elobaroted on this further, but I am talking about the version inside an anoncreds object like schema: (I thought it was present in more objects, but only schema it seems).

```rust
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Schema {
    pub name: String,
    pub version: String, <----
    pub attr_names: AttributeNames,
    pub issuer_id: IssuerId,
}

**Comment by swcurran** [comment]
Discussed on 2023.01.09 AnonCreds Spec Working Group Meeting -- add note in spec. about Indy using semver, but otherwise, it is just a string, and not validated in AnonCreds.

**Comment by rodolfomiranda** [comment]
[PR](https://github.com/hyperledger/anoncreds-spec/pull/142) created
