### ISSUE TITLE
Question the correctness of holders AnonCreds data objects diagram

### ISSUE THREAD

**Issue by wip-abramson** [hyperledger/anoncreds-spec#181]
I am wondering if the following diagram is misleading?

![image](https://github.com/hyperledger/anoncreds-spec/assets/18055112/d455ef31-f771-4e92-abe3-123756353046)

To me, interpretting this seems to imply that for every AnonCred credential that the holder recieves they must store the associated blinded link secret that they used during the issuance protocol.

I do not think that is correct. 

My understanding is that I create a blinding of my link secret that is used for the issuance protocol **BUT** as part of that protocol I remove the blinding from the signature I recieve on my credential. Removing this blinding effectively means the holder stores a valid signature - different from the one the issuer created - over the set of attributes of the credential where one of these attributes is the **unblinded** link secret. Therefore, the blinding factor and the blinded link secret used in this protocol are only relevant for the protocol itself. There is no need to store these after the protocol has been completed.

During a presentation protocol, the holder creates a fresh unlinkable blinding for their link secret and an associated proof that they know the link secret that was signed in the credential. Again, this blinding is only used for the single protocol instance. No need to persist it.

I think I would update the spec text associated with the diagram to reflect some of this. The most important point, to me at least, is that ultimately the holder stores credentials which are **a signature over a set of attributes where one attribute is their link secret**

**Comment by edeykholt** [comment]
While I don't know the answer, I see the class diagram has an association with 1..1 multiplicities on both sides, which is suspicious.

**Comment by swcurran** [comment]
A PR #183 was merged on this that updated the text about this, but the image still needs to be updated, so this issue still needs action.
