### ISSUE TITLE
w3c credentialSchema MUST include an id

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/anoncreds-spec#191]
currently it has `type`, `definition` and `schema`

> Each credentialSchema MUST specify its type (for example, JsonSchemaValidator2018), and an id [property](https://www.w3.org/TR/vc-data-model/#dfn-property) that MUST be a [URI](https://www.w3.org/TR/vc-data-model/#dfn-uri) identifying the schema file. The precise contents of each data schema is determined by the specific type definition.

**Comment by TimoGlastra** [comment]
@swcurran for the WG call later today

**Comment by swcurran** [comment]
Resolved as we sorted out the W3C VC formatting.
