### ISSUE TITLE
Propose removing the Data Flow introduction and moving the data flows out a header level

### ISSUE THREAD

**Issue by swcurran** [hyperledger/anoncreds-spec#67]
Several reasons -- the intro is not needed, and the flows are the core elements of the specification.  Also, exposes one more layer of headers in the ToC and content.  Without this, we'll need to update SpecUp to display headers in a reasonable way...

**Comment by TelegramSam** [comment]
Discussed WG 20220801 - Thumbs up from folks, no downvotes.

**Comment by swcurran** [comment]
Resolved with the merging of #69
