### ISSUE TITLE
what are the issuer_did and schema_issuer_did if not always bound to dids?

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/anoncreds-spec#74]
AnonCreds is not going to be bound to dids. It can be used with e.g. an https server. 

The current indy implementation of AnonCreds uses the `issuer_did` and `schema_issuer_did` properties, allowing you to filter credentials. Should this be updated to `issuer_id` and `schema_issuer_id`? And if so, what should the value be for the id values if not using dids as a base?

[See WQL Query](https://anoncreds-wg.github.io/anoncreds-spec/#wql-query)

**Comment by swcurran** [comment]
I suppose one options would be limit it to DIDs and for the HTTPS use case require the use of `did:web`.

The said, I know that some of the implementations have used a database, and a file.

**Comment by rodolfomiranda** [comment]
I think we can keep the spec opinionated to `DID` since many definitions and flows are DID related, but we can add a paragraph to clarify how to deal with `ids` on non-did implementations.

**Comment by swcurran** [comment]
Agreed.

**Comment by swcurran** [comment]
Closing - this has been addressed in the spec.
