### ISSUE TITLE
Change nomenclature in section 7. Terminology

### ISSUE THREAD

**Issue by morrieinmaas** [hyperledger/anoncreds-spec#77]
Parts of the terminology in section [7. Terminology](https://anoncreds-wg.github.io/anoncreds-spec/#terminology) reflects the (Indy) code style instead of a human-readable style.

Example: `CRED_DEF`

Proposal: Rename `CRED_DEF` (and all other names where applicable) to Credential Definition (and corollary).

Why: Decouples spec from specific implementation.

**Comment by swcurran** [comment]
I don't think that "CredDef" is Indy specific. In fact, in Indy it is "CLAIM_DEF", which we are avoiding.  Not particularly against making everything consistent and human-readable, but I'm not sure that is the best example.  Particularly when referencing the data structure "CRED_DEF" that is used by AnonCreds.

**Comment by TimoGlastra** [comment]
I do think it would be good to make it consistent. We have Credential Offer, and then CRED_DEF (was CLAIM_DEF) which has some history to it from indy as it is the name of the transaction: https://github.com/hyperledger/indy-node/blob/main/docs/source/transactions.md#claim_def

**Comment by morrieinmaas** [comment]
Thanks for the quick replies @swcurran @TimoGlastra. @swcurransorry that wasn't to the point about being indy specific, but a "sloppy" hint at what timo said more succinctly.

**Comment by swcurran** [comment]
So the proposal is to make all references to "CRED_DEF" to "Credential Definition" throughout the spec?  As noted, I'm OK with that in the reading, but wonder if the term CRED_DEF should be used when talking about the data model?  That said, I'm not a fan of anything with ALL CAPS and underscores so happy to see the change.

Note that we need a `[[ref: Credential Definition]]` to be used throughout, which is lots of fun.  The joys of writing a spec...

BTW -- I've asked the auther of spec-up to style references vs. external links differently. No action on that.  If you have a suggestion on what that should look like, please let me know.

**Comment by morrieinmaas** [comment]
Open to suggestions here also. "Credential Definition" was just an obvious candidate

**Comment by swcurran** [comment]
Works for me. Getting a list of all such changes, and making them is going to be fun. I've known that was coming but ignoring it for now.  But it is needed...

**Comment by morrieinmaas** [comment]
> Works for me. Getting a list of all such changes, and making them is going to be fun. I've known that was coming but ignoring it for now. But it is needed...

Nice. We'll provide a change set then and you can see if that works for you.

**Comment by swcurran** [comment]
This has been resolved in the terminology section in #193
