### ISSUE TITLE
Question: Support creating CredDefs that use a subset of the Schema Attributes?

### ISSUE THREAD

**Issue by swcurran** [hyperledger/anoncreds-spec#86]
In AnonCreds there is not a cryptographic tie between the Schema object and the CredDef object. A CredDef object can be created by passing to it a list of attributes.  A scenario has come up recently where this is a potential feature (see [Aries Cloud Agent Python issue #1971](https://github.com/hyperledger/aries-cloudagent-python/issues/1971)).  In that:

- a number of coordinating issuers want to use a common schema for a Credential, but
- the issuers each only want to use a (different) subset of the attributes
- with a completely common schema, each issuer must issue credentials with NULL for data they don't want to issue
- with a "CredDef-subset" capability, each entity could issue only the attributes they want to include

Is this a good idea?

**Comment by TelegramSam** [comment]
Discussed WG 20221107.

My comment in the WG: Weakening the schema object reduces the expectations of AnonCreds from a contextual semantics perspective. Requiring a schema object provides a foundation for governance that I believe will be vital in the growth of ecosystems.

**Comment by swcurran** [comment]
For those interested in more detail, please got to time 37:26 of this ]AnonCreds Specification Working Group Call Recording](https://wiki.hyperledger.org/display/ANONCREDS/2022-11-07+AnonCreds+Specification+Working+Group+Meeting?preview=%2F78021428%2F78021721%2F20221107+AnonCreds+Specification+Working+Group+Call+Recording.mp4) for the discussion.
